export * from './authenticate-api.service';
import { AuthenticateApiService } from './authenticate-api.service';
export * from './authenticate-api.serviceInterface';
export * from './exercises-api.service';
import { ExercisesApiService } from './exercises-api.service';
export * from './exercises-api.serviceInterface';
export * from './plans-api.service';
import { PlansApiService } from './plans-api.service';
export * from './plans-api.serviceInterface';
export * from './plans-group-api.service';
import { PlansGroupApiService } from './plans-group-api.service';
export * from './plans-group-api.serviceInterface';
export * from './users-api.service';
import { UsersApiService } from './users-api.service';
export * from './users-api.serviceInterface';
export const APIS = [AuthenticateApiService, ExercisesApiService, PlansApiService, PlansGroupApiService, UsersApiService];
