/**
 * WorkouteRR API
 * WorkouteRR REST API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SignInDto } from '../model/models';
import { SignInResponseDto } from '../model/models';
import { User } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface AuthenticateApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * Get current user
     * 
     */
    authenticateControllerCurrentUser(extraHttpRequestParams?: any): Observable<User>;

    /**
     * sign-in
     * 
     * @param signInDto 
     */
    authenticateControllerSignIn(signInDto: SignInDto, extraHttpRequestParams?: any): Observable<SignInResponseDto>;

}
