/**
 * WorkouteRR API
 * WorkouteRR REST API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { ApiConfiguration }                                     from '../configuration';



export interface DefaultApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * 
     * 
     */
    authControllerGetProfile(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    authControllerLogin(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param body 
     */
    exercisesControllerCreate(body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    exercisesControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    exercisesControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    exercisesControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param body 
     */
    exercisesControllerUpdate(id: string, body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param body 
     */
    plansControllerCreate(body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    plansControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    plansControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    plansControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param body 
     */
    plansControllerUpdate(id: string, body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param body 
     */
    plansGroupsControllerCreate(body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    plansGroupsControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    plansGroupsControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    plansGroupsControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param body 
     */
    plansGroupsControllerUpdate(id: string, body: object, extraHttpRequestParams?: any): Observable<{}>;

}
