/**
 * WorkouteRR API
 * WorkouteRR REST API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreatePlanDto } from '../model/models';
import { Plan } from '../model/models';
import { UpdatePlanDto } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface PlansApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * Create plan
     * 
     * @param createPlanDto 
     */
    plansControllerCreate(createPlanDto: CreatePlanDto, extraHttpRequestParams?: any): Observable<Plan>;

    /**
     * Find plans
     * 
     * @param name 
     */
    plansControllerFind(name: string, extraHttpRequestParams?: any): Observable<Plan>;

    /**
     * Get plan details
     * 
     * @param id 
     */
    plansControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<Plan>;

    /**
     * Delete plan
     * 
     * @param id 
     */
    plansControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update plan
     * 
     * @param id 
     * @param updatePlanDto 
     */
    plansControllerUpdate(id: string, updatePlanDto: UpdatePlanDto, extraHttpRequestParams?: any): Observable<Plan>;

}
