/**
 * WorkouteRR API
 * WorkouteRR REST API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreatePlansGroupDto } from '../model/models';
import { PlansGroup } from '../model/models';
import { UpdatePlansGroupDto } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface PlansGroupApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * Create plans group
     * 
     * @param createPlansGroupDto 
     */
    plansGroupsControllerCreate(createPlansGroupDto: CreatePlansGroupDto, extraHttpRequestParams?: any): Observable<PlansGroup>;

    /**
     * Get plans groups
     * 
     * @param name 
     */
    plansGroupsControllerFind(name: string, extraHttpRequestParams?: any): Observable<Array<PlansGroup>>;

    /**
     * Get plans group details
     * 
     * @param id 
     */
    plansGroupsControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<PlansGroup>;

    /**
     * Delete plan group
     * 
     * @param id 
     */
    plansGroupsControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update plans group
     * 
     * @param id 
     * @param updatePlansGroupDto 
     */
    plansGroupsControllerUpdate(id: string, updatePlansGroupDto: UpdatePlansGroupDto, extraHttpRequestParams?: any): Observable<PlansGroup>;

}
