/**
 * WorkouteRR API
 * WorkouteRR REST API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserDto } from '../model/models';
import { UpdateUserDto } from '../model/models';
import { User } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface UsersApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * Create user
     * 
     * @param createUserDto 
     */
    usersControllerCreate(createUserDto: CreateUserDto, extraHttpRequestParams?: any): Observable<User>;

    /**
     * Get all users
     * 
     */
    usersControllerFindAll(extraHttpRequestParams?: any): Observable<Array<User>>;

    /**
     * Get user details
     * 
     * @param id 
     */
    usersControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<User>;

    /**
     * Delete user
     * 
     * @param id 
     */
    usersControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update user
     * 
     * @param id 
     * @param updateUserDto 
     */
    usersControllerUpdate(id: string, updateUserDto: UpdateUserDto, extraHttpRequestParams?: any): Observable<User>;

}
